### ISSUE TITLE
Cannot remove 'once' listener.

### ISSUE THREAD

**Issue by malversan** [etissieres/PyEventEmitter#4]
Issue as of version 1.0.3:

As 'once' listeners are stored inside a wrapper, the .remove() method cannot find and remove them. Even worse, it raises a ValueError exception.

The solution I implemented is simple. Instead of storing listeners as a list, store them as a dictionary using listener functions as keys. No need to store a wrapper, the 'once' flag is stored in each dictionary item and taken into account when emitting the event.

```
	def on(self, event, listener):
		if not event in self._events:
			self._events[event] = {}
		self._events[event][listener] = False

	def once(self, event, listener):
		self.on(event, listener)
		self._events[event][listener] = True

	def emit(self, event, *args, **kwargs):
		if event in self._events:
			# 'once' may delete items while iterating over listeners -> we use a copy
			listeners = self._events[event].copy()
			for listener in listeners:
				# Delete 'once' listener.
				if listeners[listener]:
					del self._events[event][listener]
				# Execute listener.
				listener(*args, **kwargs)

	def remove(self, event, listener):
		if event in self._events:
			del self._events[event][listener]

	def remove_all(self, event):
		if event in self._events:
			self._events[event] = {}

```
The rest of methods are unmodified.

As a side advantage, in the future additional flags or data could be stored for each listener item. But then instead of dict.copy() (shallow copy) you should better use copy.deepcopy() when emitting the event.

**Comment by etissieres** [comment]
Hi

Thanks a lot for reporting this.

I like your solution to fix it but it breaks compatibility with older versions, and I'm a bit uncomfortable about this. Indeed, older versions allow the same listener to be registered several times. Using the listener as a key makes this impossible. So I prefer to put an 'is_once' attribute on the function instead. I keep your idea of moving the 'once' listener removing logic to the 'emit' function rather than the 'once' function.
Here is the [fix commit](https://github.com/etissieres/PyEventEmitter/commit/0978c883a0007048759e649a13818e3dabe7e25f)

I will publish a 1.0.4 release soon.

**Comment by malversan** [comment]
Nice to see your clean solution.

For the moment I will keep my solution anyway, as in my case I do not see
the need of registering the same listener several times.

As a suggestion, I needed and added another feature to my modification:
listener priorities.

Now I add a numeric attribute ”priority” to every listener, specified as an
optional parameter when registering them with ”on” and ”once”.

The listener priority can be negative or positive (by default it is 0), and
a higher number means higher priority. As a syntactic sugar, I have also
predefined some priority values in an ”EventPriority” enumeration:
LAST,
LOW,
UNDER_NORMAL,
NORMAL = 0,
OVER_NORMAL,
HIGH,
FIRST,
CRITICAL

Then it is just a matter of reverse-sorting the list of listeners in the
”emit” method before calling them, using as sort-key function a lambda that
returns the listener ”priority” attribute.

Hope it seems a good improvement for your package.

Regards. And thanks a lot for your work.


El 5/6/2017 0:17, "Etienne Tissières" <notifications@github.com> escribió:

Hi

Thanks a lot for reporting this.

I like your solution to fix it but it breaks compatibility with older
versions, and I'm a bit uncomfortable about this. Indeed, older versions
allow the same listener to be registered several times. Using the listener
as a key makes this impossible. So I prefer to put an 'is_once' attribute
on the function instead. I keep your idea of moving the 'once' listener
removing logic to the 'emit' function rather than the 'once' function.
Here is the fix commit
<https://github.com/etissieres/PyEventEmitter/commit/0978c883a0007048759e649a13818e3dabe7e25f>

I will publish a 1.0.4 release soon.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/etissieres/PyEventEmitter/issues/4#issuecomment-306070977>,
or mute the thread
